package week_3_7;

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class FibonacciEvens {
    
    public static void main(String[] args) {
        System.out.println("fibonacciEvens() -> " + fibonacciEvens());
    }
    
    public static long fibonacciEvens() {
        long ans = 2;
        long lastNum = 2;
        long num = 3;
        long temp = 0;
        do {
            if (num % 2 == 0) {
                ans += num;
            }
            temp = num;
            num += lastNum;
            lastNum = temp;
        } while (num <= 4000000);
        return ans;
    }
}
